### ISSUE TITLE
Get EU report into http://community.openspending.org/ - wiki version

### ISSUE THREAD

**Issue by danfowler** [openspending/community.openspending.org#38] opened 2015-06-27 08:11 UTC
- [x] Take into account most recent changes in response to public comments
- [x] Determine whether to represent Funds/Datasets databases as Jekyll collections or not
- [x] Replace remaining Google URL redirects (a symptom of working in Google Docs)
- [x] Add navigation
- [x] Re-add formatting (bold, italics)
- [x] Add @pzwsk to repo
- [x] Make sure Markdown supports footnotes
- [x] Remove old EU report from /resources/eu/
- [x] Create scaffolding for new content
- [x] /resources/eu/img/ = directory for all images
- [x] review /resources/eu/  - base page. Front matter plus exec summary plus table of contents
- [x] review /resources/eu/glossary/ = “glossary section”
- [x] review /resources/eu/overview/ = “at a glance” section
- [x] review /resources/eu/revenue/ (or /resources/eu/where-does-money-come-from/)
- [x] review /resources/eu/expenditure/ - Who Manages and Spends the Money, and How? section
- [x] review /resources/eu/transparency/ =  How Transparent is the EU Budget?
- [x] review /resources/eu/research/ = Journalistic Investigations and Transparency Projects to Follow the Money
- [x] /resources/eu/funds/ = Funds Database
- [x] /resources/eu/datasets/ = annex 2. 
## Funds Database

home page: 
content from p.19-20 - “where does the money go”
only addition - at bottom after 5 special funds have separate / new heading and then add list of _all_ funds with link and brief description maybe (auto generate by iterating over funds)

Individual pages e.g. /resources/eu/funds/cohesion-fund/

let’s download the spreadsheet and convert to individual pages - 1 per fund. suggest naming in obvious way.
all metadata becomes frontmatter except column P which becomes body
we probably need to clean this up later
feel free to drop columns and we can re-add later
for 5 special funds with their own section  - overwrite content with the longer content

page layout for each fund like the sections in the main section (e.g. p. 20 - cohesion fund)
summary box then content
summary box will likely not have all frontmatter info atm
## Datasets Database

Then one page each (mini db again) for each dataset

Only rows 2,3,4 of spreadsheet
Financial Transparency System /resources/eu/datasets/financial-transparency-system/
Grant and contributions awarded in the field of humanitarian aid
Horizon 2020 (CORDIS)
- the following
  common-agricultural-policy-cap
  common-fisheries-policy-cfp
  european-regional-development-fund-and-cohesion-fund
  Only have col B,C,D,F,L as frontmatter and description as body

**Comment by danfowler** [comment] 2015-06-27 13:18
@pzwsk let me know when you have time to chat.  Currently I'm on Bangkok time.

**Comment by danfowler** [comment] 2015-06-28 08:19
OK, I uploaded the full export of the report into Markdown from the Google Docs: https://github.com/openspending/dotorg/blob/gh-pages/resources/eu/export.md

I suggest we just split the sections of this document into their respective folders and clean up from there.  For some reason, styles like bold and italic aren't preserved.

**Comment by danfowler** [comment] 2015-06-28 15:51
Lots of content in its right place, but would be worth examining each section for formatting issues, organization, etc.  Open Data audit still to be added.

**Comment by danfowler** [comment] 2015-06-29 15:10
@rgrp re: /resources/eu/datasets/, rows 2,3,4 are in, for the rest, should the permalinks be something like: 
- /resources/eu/datasets/common-agricultural-policy-cap-fr
- /resources/eu/datasets/common-agricultural-policy-cap-gr
- /resources/eu/datasets/common-agricultural-policy-cap-pl
- ...

**Comment by rufuspollock** [comment] 2015-06-29 15:13
@danfowler that url structure looks great.

**Comment by pzwsk** [comment] 2015-06-29 17:06
Hi Daniel, I am planning to work on EU budget next week and I am available
for a call as of Tuesday July 7th. Would a call that day be ok for you ?

Thanks
Pierre

Le sam 27 juin 2015 15:18, Daniel Fowler notifications@github.com a
écrit :

**Comment by rufuspollock** [comment] 2015-06-29 19:03
@pzwsk the issue is the planned release date was _this_ wednesday - not next week ;-) (Have you seen the skype chat thread on this).

**Comment by rufuspollock** [comment] 2015-07-09 14:48
@danfowler one issue i just noticed re datasets list http://community.openspending.org/resources/eu/datasets/
- Currently we have listed all the local country funds e.g. Beneficiaries of the Common Agricultural Policy (Austria). IIRC when we discussed plan was just to have one dataset entry namely "Common Agricultural Policy" and not break down by country. Ditto for cohesion policy
- I would remove the link to the spreadsheet given that we have all the info on this page

Could we make this change asap as I would like to share this page with people and atm it is a bit unusable (as dozens of CAP or cohesion fund items which are basically empty of info).

**Comment by danfowler** [comment] 2015-07-09 17:43
Is this more in line with what you were thinking: http://community.openspending.org/resources/eu/datasets/

**Comment by rufuspollock** [comment] 2015-07-10 08:33
@danfowler perfect!

And I guess we can close this issue - hurrah!

**Comment by danfowler** [comment] 2015-07-10 14:03
Yay!

**Closed as completed** 2015-07-10 14:02 UTC

**Comment by danfowler** [comment] 2015-07-10 15:12
Oh, and report navigation added to sidebar menu.
